spring:
  profiles:
    active:
    - dev

 ---
 spring:
   profiles: dev
   application:
     name: SCloud-config-Center-Dev

---
spring:
  profiles: test
  application:
    name: SCloud-config-Center-Test